version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
          - node_modules
          - ~/.npm 
          - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test

  deploy:
    docker: # Use the Docker executor for the deploy job
      - image: circleci/node:12.9.1-browsers  # Specify the Docker image to use for the deploy job
    steps:
      - checkout
      - run: npm run build
      - aws-s3/sync:
          from: build
          to: 's3://translator-app/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true

workflows: # Define a Workflow running the build job, then the deploy job
  version: 2
  build-deploy: # Make a workflow to build and deploy your project
    jobs:
      - build
      - deploy:
          requires:
          - build
          filters:
            branches:
              only: main
